include:
  - board: nice_nano_v2
    shield: klor_left
  - board: nice_nano_v2
    shield: klor_right
  - board: seeeduino_xiao_ble
    shield: klor_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
