# build.yaml
include:
  # KLOR halves (nice!nano v2)
  - board: nice_nano_v2
    shield: klor_left
  - board: nice_nano_v2
    shield: klor_right

  # Prospector dongle (central) on Seeeduino XIAO BLE
  # Use your keyboard's "_dongle" shield + prospector_adapter
  - board: seeeduino_xiao_ble
    shield: klor_dongle prospector_adapter