include:
  - board: nice_nano_v2
    shield: klor_left
  - board: nice_nano_v2
    shield: klor_right
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: "klor_dongle prospector_adapter"
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: seeeduino_xiao_ble
    shield: settings_reset

