# config/west.yml
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: carrefinho
      url-base: https://github.com/carrefinho
  projects:
    - name: zmk
      remote: zmkfirmware
      # TIP: prospector can be sensitive to upstream changes; pin ZMK (see note below)
      revision: v0.2
      import: app/west.yml
    - name: prospector-zmk-module
      remote: carrefinho
      revision: main
  self:
    path: config